baseurl = "https://nekrut.github.io/BMMB554/"
languageCode = "en-us"
title = "BMMB 554 / 2017"
theme = "hugo-theme-blueberry-detox"
paginate = 10


[params]
	author = "Anton Nekrutenko"
	description = "Introduction to data driven life sciences"
	